from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.browse_button = QtGui.QPushButton(self.centralwidget)
        self.browse_button.setGeometry(QtCore.QRect(200, 60, 85, 21))
        self.browse_button.setObjectName(_fromUtf8("browse_button"))
        self.browse_label = QtGui.QLabel(self.centralwidget)
        self.browse_label.setGeometry(QtCore.QRect(20, 60, 181, 21))
        self.browse_label.setObjectName(_fromUtf8("browse_label"))
        self.browse_text = QtGui.QLineEdit(self.centralwidget)
        self.browse_text.setGeometry(QtCore.QRect(30, 90, 251, 25))
        self.browse_text.setObjectName(_fromUtf8("browse_text"))
        self.browse_import = QtGui.QPushButton(self.centralwidget)
        self.browse_import.setGeometry(QtCore.QRect(30, 120, 251, 26))
        self.browse_import.setObjectName(_fromUtf8("browse_import"))
        self.id_label = QtGui.QLabel(self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(20, 200, 261, 16))
        self.id_label.setObjectName(_fromUtf8("id_label"))
        self.id_color = QtGui.QComboBox(self.centralwidget)
        self.id_color.setGeometry(QtCore.QRect(30, 250, 121, 31))
        self.id_color.setObjectName(_fromUtf8("id_color"))
        self.id_color.addItem(_fromUtf8(""))
        self.id_color.addItem(_fromUtf8(""))
        self.id_color.addItem(_fromUtf8(""))
        self.id_color.addItem(_fromUtf8(""))
        self.id_color.addItem(_fromUtf8(""))
        self.id_color.addItem(_fromUtf8(""))
        self.id_color.addItem(_fromUtf8(""))
        self.id_car = QtGui.QSpinBox(self.centralwidget)
        self.id_car.setGeometry(QtCore.QRect(150, 250, 71, 31))
        self.id_car.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.id_car.setObjectName(_fromUtf8("id_car"))
        self.id_car_label = QtGui.QLabel(self.centralwidget)
        self.id_car_label.setGeometry(QtCore.QRect(30, 230, 141, 16))
        self.id_car_label.setObjectName(_fromUtf8("id_car_label"))
        self.id_person_label = QtGui.QLabel(self.centralwidget)
        self.id_person_label.setGeometry(QtCore.QRect(230, 230, 71, 16))
        self.id_person_label.setObjectName(_fromUtf8("id_person_label"))
        self.id_person = QtGui.QLineEdit(self.centralwidget)
        self.id_person.setGeometry(QtCore.QRect(230, 250, 71, 31))
        self.id_person.setObjectName(_fromUtf8("id_person"))
        self.sync_label = QtGui.QLabel(self.centralwidget)
        self.sync_label.setGeometry(QtCore.QRect(20, 330, 241, 16))
        self.sync_label.setObjectName(_fromUtf8("sync_label"))
        self.sync_number = QtGui.QLabel(self.centralwidget)
        self.sync_number.setGeometry(QtCore.QRect(30, 360, 121, 16))
        self.sync_number.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sync_number.setObjectName(_fromUtf8("sync_number"))
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(160, 360, 61, 21))
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setMaximum(100000)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.sync_time = QtGui.QLabel(self.centralwidget)
        self.sync_time.setGeometry(QtCore.QRect(30, 390, 121, 16))
        self.sync_time.setObjectName(_fromUtf8("sync_time"))
        self.timeEdit = QtGui.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(130, 390, 91, 25))
        self.timeEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.status_bar = QtGui.QProgressBar(self.centralwidget)
        self.status_bar.setGeometry(QtCore.QRect(0, 530, 791, 23))
        self.status_bar.setProperty("value", 24)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 500, 801, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(390, 0, 20, 511))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAsdlfh = QtGui.QAction(MainWindow)
        self.actionAsdlfh.setObjectName(_fromUtf8("actionAsdlfh"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Import Interface", None))
        self.browse_button.setText(_translate("MainWindow", "Browse", None))
        self.browse_label.setText(_translate("MainWindow", "1) Select Drive With SD Card", None))
        self.browse_import.setText(_translate("MainWindow", "Import", None))
        self.id_label.setText(_translate("MainWindow", "2) Input identification information", None))
        self.id_color.setItemText(0, _translate("MainWindow", "Red", None))
        self.id_color.setItemText(1, _translate("MainWindow", "Green", None))
        self.id_color.setItemText(2, _translate("MainWindow", "Blue", None))
        self.id_color.setItemText(3, _translate("MainWindow", "Yellow", None))
        self.id_color.setItemText(4, _translate("MainWindow", "Black", None))
        self.id_color.setItemText(5, _translate("MainWindow", "White", None))
        self.id_color.setItemText(6, _translate("MainWindow", "Orange", None))
        self.id_car_label.setText(_translate("MainWindow", "Car color and number", None))
        self.id_person_label.setText(_translate("MainWindow", "Individual", None))
        self.sync_label.setText(_translate("MainWindow", "3) Synchronize image information", None))
        self.sync_number.setText(_translate("MainWindow", "First image number", None))
        self.sync_time.setText(_translate("MainWindow", "First image time", None))
        self.actionAsdlfh.setText(_translate("MainWindow", "asdlfh", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

