# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageForm.ui'
#
# Created: Sun Feb 22 00:03:04 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImageForm(object):
    def setupUi(self, ImageForm):
        ImageForm.setObjectName(_fromUtf8("ImageForm"))
        ImageForm.resize(582, 647)
        ImageForm.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        ImageForm.setFont(font)
        ImageForm.setStyleSheet(_fromUtf8(""))
        self.horizontalLayout = QtGui.QHBoxLayout(ImageForm)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.layout = QtGui.QVBoxLayout()
        self.layout.setSpacing(15)
        self.layout.setObjectName(_fromUtf8("layout"))
        self.drive_layout = QtGui.QGroupBox(ImageForm)
        self.drive_layout.setMinimumSize(QtCore.QSize(0, 129))
        self.drive_layout.setMaximumSize(QtCore.QSize(16777215, 129))
        self.drive_layout.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.drive_layout.setFont(font)
        self.drive_layout.setStyleSheet(_fromUtf8("font-size:20px;"))
        self.drive_layout.setFlat(False)
        self.drive_layout.setObjectName(_fromUtf8("drive_layout"))
        self.formLayout = QtGui.QFormLayout(self.drive_layout)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(-1, 12, -1, -1)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.drive_browse = QtGui.QPushButton(self.drive_layout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drive_browse.sizePolicy().hasHeightForWidth())
        self.drive_browse.setSizePolicy(sizePolicy)
        self.drive_browse.setMinimumSize(QtCore.QSize(0, 45))
        self.drive_browse.setIconSize(QtCore.QSize(20, 20))
        self.drive_browse.setObjectName(_fromUtf8("drive_browse"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.drive_browse)
        self.drive_display = QtGui.QLabel(self.drive_layout)
        self.drive_display.setStyleSheet(_fromUtf8("color:#666;"))
        self.drive_display.setAlignment(QtCore.Qt.AlignCenter)
        self.drive_display.setWordWrap(False)
        self.drive_display.setObjectName(_fromUtf8("drive_display"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.drive_display)
        self.layout.addWidget(self.drive_layout)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.layout.addItem(spacerItem)
        self.id_layout = QtGui.QGroupBox(ImageForm)
        self.id_layout.setMinimumSize(QtCore.QSize(0, 150))
        self.id_layout.setMaximumSize(QtCore.QSize(16777215, 150))
        self.id_layout.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.id_layout.setFont(font)
        self.id_layout.setStyleSheet(_fromUtf8("font-size:20px;"))
        self.id_layout.setFlat(False)
        self.id_layout.setCheckable(False)
        self.id_layout.setChecked(False)
        self.id_layout.setObjectName(_fromUtf8("id_layout"))
        self.formLayout_4 = QtGui.QFormLayout(self.id_layout)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setContentsMargins(-1, 12, -1, -1)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.color_label = QtGui.QLabel(self.id_layout)
        self.color_label.setMinimumSize(QtCore.QSize(159, 0))
        self.color_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.color_label.setObjectName(_fromUtf8("color_label"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.color_label)
        self.color_input_space = QtGui.QVBoxLayout()
        self.color_input_space.setObjectName(_fromUtf8("color_input_space"))
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.color_input_space)
        self.id_label = QtGui.QLabel(self.id_layout)
        self.id_label.setMinimumSize(QtCore.QSize(159, 0))
        self.id_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.id_label.setObjectName(_fromUtf8("id_label"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.id_label)
        self.letter_input = QtGui.QComboBox(self.id_layout)
        self.letter_input.setMinimumSize(QtCore.QSize(0, 30))
        self.letter_input.setObjectName(_fromUtf8("letter_input"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.letter_input)
        self.number_input = QtGui.QComboBox(self.id_layout)
        self.number_input.setMinimumSize(QtCore.QSize(0, 30))
        self.number_input.setObjectName(_fromUtf8("number_input"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.number_input)
        self.numer_label = QtGui.QLabel(self.id_layout)
        self.numer_label.setMinimumSize(QtCore.QSize(159, 0))
        self.numer_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.numer_label.setObjectName(_fromUtf8("numer_label"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.numer_label)
        self.layout.addWidget(self.id_layout)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.layout.addItem(spacerItem1)
        self.sync_layout = QtGui.QGroupBox(ImageForm)
        self.sync_layout.setMinimumSize(QtCore.QSize(0, 154))
        self.sync_layout.setMaximumSize(QtCore.QSize(16777215, 154))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.sync_layout.setFont(font)
        self.sync_layout.setStyleSheet(_fromUtf8("font-size:20px;"))
        self.sync_layout.setFlat(False)
        self.sync_layout.setObjectName(_fromUtf8("sync_layout"))
        self.formLayout_6 = QtGui.QFormLayout(self.sync_layout)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(-1, 12, -1, -1)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.name_label = QtGui.QLabel(self.sync_layout)
        self.name_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.name_label)
        self.name_input = QtGui.QLineEdit(self.sync_layout)
        self.name_input.setMinimumSize(QtCore.QSize(0, 30))
        self.name_input.setAlignment(QtCore.Qt.AlignCenter)
        self.name_input.setObjectName(_fromUtf8("name_input"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.name_input)
        self.time_label = QtGui.QLabel(self.sync_layout)
        self.time_label.setMinimumSize(QtCore.QSize(159, 0))
        self.time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.time_label.setObjectName(_fromUtf8("time_label"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.time_label)
        self.time_input = QtGui.QTimeEdit(self.sync_layout)
        self.time_input.setMinimumSize(QtCore.QSize(0, 30))
        self.time_input.setStyleSheet(_fromUtf8(""))
        self.time_input.setAlignment(QtCore.Qt.AlignCenter)
        self.time_input.setReadOnly(False)
        self.time_input.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.time_input.setObjectName(_fromUtf8("time_input"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.time_input)
        self.label = QtGui.QLabel(self.sync_layout)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color:#666;"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.label)
        self.layout.addWidget(self.sync_layout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.layout.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.layout)

        self.retranslateUi(ImageForm)
        QtCore.QMetaObject.connectSlotsByName(ImageForm)

    def retranslateUi(self, ImageForm):
        ImageForm.setWindowTitle(_translate("ImageForm", "Form", None))
        self.drive_layout.setTitle(_translate("ImageForm", "Step 1 - SD Card", None))
        self.drive_browse.setText(_translate("ImageForm", "Browse", None))
        self.drive_display.setText(_translate("ImageForm", "Select a Directory", None))
        self.id_layout.setTitle(_translate("ImageForm", "Step 2 - Identification", None))
        self.color_label.setText(_translate("ImageForm", "Car Color", None))
        self.id_label.setText(_translate("ImageForm", "Person Letter", None))
        self.numer_label.setText(_translate("ImageForm", "Car Number", None))
        self.sync_layout.setTitle(_translate("ImageForm", "Step 3 - Synchronize", None))
        self.name_label.setText(_translate("ImageForm", "First Image Name", None))
        self.time_label.setText(_translate("ImageForm", "First Image Time", None))
        self.time_input.setDisplayFormat(_translate("ImageForm", "HH:mm", None))
        self.label.setText(_translate("ImageForm", "Specify image name", None))

